// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: customer.sql

package db

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (name, phone, email, image, email_verified, nid, status) 
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, name, phone, email, image, email_verified, nid, status, created_at, updated_at
`

type CreateCustomerParams struct {
	Name          string `json:"name"`
	Phone         string `json:"phone"`
	Email         string `json:"email"`
	Image         string `json:"image"`
	EmailVerified bool   `json:"email_verified"`
	Nid           string `json:"nid"`
	Status        string `json:"status"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.queryRow(ctx, q.createCustomerStmt, createCustomer,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Image,
		arg.EmailVerified,
		arg.Nid,
		arg.Status,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Image,
		&i.EmailVerified,
		&i.Nid,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCustomerAddress = `-- name: CreateCustomerAddress :one
INSERT INTO customer_addresses (customer_id, label, address, geo_point, apartment, area, floor)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, customer_id, label, address, geo_point, apartment, area, floor, created_at
`

type CreateCustomerAddressParams struct {
	CustomerID int64       `json:"customer_id"`
	Label      string      `json:"label"`
	Address    string      `json:"address"`
	GeoPoint   interface{} `json:"geo_point"`
	Apartment  string      `json:"apartment"`
	Area       string      `json:"area"`
	Floor      string      `json:"floor"`
}

func (q *Queries) CreateCustomerAddress(ctx context.Context, arg CreateCustomerAddressParams) (CustomerAddress, error) {
	row := q.queryRow(ctx, q.createCustomerAddressStmt, createCustomerAddress,
		arg.CustomerID,
		arg.Label,
		arg.Address,
		arg.GeoPoint,
		arg.Apartment,
		arg.Area,
		arg.Floor,
	)
	var i CustomerAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Label,
		&i.Address,
		&i.GeoPoint,
		&i.Apartment,
		&i.Area,
		&i.Floor,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, phone, email, image, email_verified, nid, status, created_at, updated_at FROM customers WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id int64) (Customer, error) {
	row := q.queryRow(ctx, q.getCustomerStmt, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Image,
		&i.EmailVerified,
		&i.Nid,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerAddress = `-- name: GetCustomerAddress :one
SELECT id, customer_id, label, address, geo_point, apartment, area, floor, created_at FROM customer_addresses WHERE id = $1
`

func (q *Queries) GetCustomerAddress(ctx context.Context, id int64) (CustomerAddress, error) {
	row := q.queryRow(ctx, q.getCustomerAddressStmt, getCustomerAddress, id)
	var i CustomerAddress
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Label,
		&i.Address,
		&i.GeoPoint,
		&i.Apartment,
		&i.Area,
		&i.Floor,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomerAddresses = `-- name: ListCustomerAddresses :many
SELECT id, customer_id, label, address, geo_point, apartment, area, floor, created_at FROM customer_addresses WHERE customer_id = $1
`

func (q *Queries) ListCustomerAddresses(ctx context.Context, customerID int64) ([]CustomerAddress, error) {
	rows, err := q.query(ctx, q.listCustomerAddressesStmt, listCustomerAddresses, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerAddress{}
	for rows.Next() {
		var i CustomerAddress
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Label,
			&i.Address,
			&i.GeoPoint,
			&i.Apartment,
			&i.Area,
			&i.Floor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
