// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countCategoriesStmt, err = db.PrepareContext(ctx, countCategories); err != nil {
		return nil, fmt.Errorf("error preparing query CountCategories: %w", err)
	}
	if q.countCategoriesByBrandIDStmt, err = db.PrepareContext(ctx, countCategoriesByBrandID); err != nil {
		return nil, fmt.Errorf("error preparing query CountCategoriesByBrandID: %w", err)
	}
	if q.countInventoryHistoryStmt, err = db.PrepareContext(ctx, countInventoryHistory); err != nil {
		return nil, fmt.Errorf("error preparing query CountInventoryHistory: %w", err)
	}
	if q.countInventoryHistoryByProductIdStmt, err = db.PrepareContext(ctx, countInventoryHistoryByProductId); err != nil {
		return nil, fmt.Errorf("error preparing query CountInventoryHistoryByProductId: %w", err)
	}
	if q.countProductInventoryStmt, err = db.PrepareContext(ctx, countProductInventory); err != nil {
		return nil, fmt.Errorf("error preparing query CountProductInventory: %w", err)
	}
	if q.countProductInventoryByProductIdStmt, err = db.PrepareContext(ctx, countProductInventoryByProductId); err != nil {
		return nil, fmt.Errorf("error preparing query CountProductInventoryByProductId: %w", err)
	}
	if q.countProductVariantItemsStmt, err = db.PrepareContext(ctx, countProductVariantItems); err != nil {
		return nil, fmt.Errorf("error preparing query CountProductVariantItems: %w", err)
	}
	if q.countProductVariantsStmt, err = db.PrepareContext(ctx, countProductVariants); err != nil {
		return nil, fmt.Errorf("error preparing query CountProductVariants: %w", err)
	}
	if q.countProductsStmt, err = db.PrepareContext(ctx, countProducts); err != nil {
		return nil, fmt.Errorf("error preparing query CountProducts: %w", err)
	}
	if q.countProductsByBrandIDStmt, err = db.PrepareContext(ctx, countProductsByBrandID); err != nil {
		return nil, fmt.Errorf("error preparing query CountProductsByBrandID: %w", err)
	}
	if q.countProductsByCategoryIDStmt, err = db.PrepareContext(ctx, countProductsByCategoryID); err != nil {
		return nil, fmt.Errorf("error preparing query CountProductsByCategoryID: %w", err)
	}
	if q.countProductsByVendorIDStmt, err = db.PrepareContext(ctx, countProductsByVendorID); err != nil {
		return nil, fmt.Errorf("error preparing query CountProductsByVendorID: %w", err)
	}
	if q.countVendorsStmt, err = db.PrepareContext(ctx, countVendors); err != nil {
		return nil, fmt.Errorf("error preparing query CountVendors: %w", err)
	}
	if q.countZonesStmt, err = db.PrepareContext(ctx, countZones); err != nil {
		return nil, fmt.Errorf("error preparing query CountZones: %w", err)
	}
	if q.countZonesByBrandIDStmt, err = db.PrepareContext(ctx, countZonesByBrandID); err != nil {
		return nil, fmt.Errorf("error preparing query CountZonesByBrandID: %w", err)
	}
	if q.createBrandStmt, err = db.PrepareContext(ctx, createBrand); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBrand: %w", err)
	}
	if q.createBrandCategoryStmt, err = db.PrepareContext(ctx, createBrandCategory); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBrandCategory: %w", err)
	}
	if q.createBrandZoneStmt, err = db.PrepareContext(ctx, createBrandZone); err != nil {
		return nil, fmt.Errorf("error preparing query CreateBrandZone: %w", err)
	}
	if q.createCategoryStmt, err = db.PrepareContext(ctx, createCategory); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCategory: %w", err)
	}
	if q.createInventoryHistoryStmt, err = db.PrepareContext(ctx, createInventoryHistory); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInventoryHistory: %w", err)
	}
	if q.createOperationTimeStmt, err = db.PrepareContext(ctx, createOperationTime); err != nil {
		return nil, fmt.Errorf("error preparing query CreateOperationTime: %w", err)
	}
	if q.createProductStmt, err = db.PrepareContext(ctx, createProduct); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProduct: %w", err)
	}
	if q.createProductInventoryStmt, err = db.PrepareContext(ctx, createProductInventory); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProductInventory: %w", err)
	}
	if q.createProductVariantStmt, err = db.PrepareContext(ctx, createProductVariant); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProductVariant: %w", err)
	}
	if q.createProductVariantItemStmt, err = db.PrepareContext(ctx, createProductVariantItem); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProductVariantItem: %w", err)
	}
	if q.createVendorStmt, err = db.PrepareContext(ctx, createVendor); err != nil {
		return nil, fmt.Errorf("error preparing query CreateVendor: %w", err)
	}
	if q.createVendorUserStmt, err = db.PrepareContext(ctx, createVendorUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateVendorUser: %w", err)
	}
	if q.createZoneStmt, err = db.PrepareContext(ctx, createZone); err != nil {
		return nil, fmt.Errorf("error preparing query CreateZone: %w", err)
	}
	if q.deleteBrandStmt, err = db.PrepareContext(ctx, deleteBrand); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBrand: %w", err)
	}
	if q.deleteBrandCategoryStmt, err = db.PrepareContext(ctx, deleteBrandCategory); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBrandCategory: %w", err)
	}
	if q.deleteBrandZoneStmt, err = db.PrepareContext(ctx, deleteBrandZone); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteBrandZone: %w", err)
	}
	if q.deleteCategoryStmt, err = db.PrepareContext(ctx, deleteCategory); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteCategory: %w", err)
	}
	if q.deleteInventoryHistoryStmt, err = db.PrepareContext(ctx, deleteInventoryHistory); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteInventoryHistory: %w", err)
	}
	if q.deleteOperationTimeStmt, err = db.PrepareContext(ctx, deleteOperationTime); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteOperationTime: %w", err)
	}
	if q.deleteProductStmt, err = db.PrepareContext(ctx, deleteProduct); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProduct: %w", err)
	}
	if q.deleteProductInventoryStmt, err = db.PrepareContext(ctx, deleteProductInventory); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProductInventory: %w", err)
	}
	if q.deleteProductVariantStmt, err = db.PrepareContext(ctx, deleteProductVariant); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProductVariant: %w", err)
	}
	if q.deleteProductVariantItemStmt, err = db.PrepareContext(ctx, deleteProductVariantItem); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteProductVariantItem: %w", err)
	}
	if q.deleteVendorStmt, err = db.PrepareContext(ctx, deleteVendor); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteVendor: %w", err)
	}
	if q.deleteVendorUserStmt, err = db.PrepareContext(ctx, deleteVendorUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteVendorUser: %w", err)
	}
	if q.deleteZoneStmt, err = db.PrepareContext(ctx, deleteZone); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteZone: %w", err)
	}
	if q.getBrandStmt, err = db.PrepareContext(ctx, getBrand); err != nil {
		return nil, fmt.Errorf("error preparing query GetBrand: %w", err)
	}
	if q.getBrandCategoryStmt, err = db.PrepareContext(ctx, getBrandCategory); err != nil {
		return nil, fmt.Errorf("error preparing query GetBrandCategory: %w", err)
	}
	if q.getCategoryStmt, err = db.PrepareContext(ctx, getCategory); err != nil {
		return nil, fmt.Errorf("error preparing query GetCategory: %w", err)
	}
	if q.getInventoryHistoryStmt, err = db.PrepareContext(ctx, getInventoryHistory); err != nil {
		return nil, fmt.Errorf("error preparing query GetInventoryHistory: %w", err)
	}
	if q.getInventoryHistoryByProductIDStmt, err = db.PrepareContext(ctx, getInventoryHistoryByProductID); err != nil {
		return nil, fmt.Errorf("error preparing query GetInventoryHistoryByProductID: %w", err)
	}
	if q.getOperationTimeStmt, err = db.PrepareContext(ctx, getOperationTime); err != nil {
		return nil, fmt.Errorf("error preparing query GetOperationTime: %w", err)
	}
	if q.getProductStmt, err = db.PrepareContext(ctx, getProduct); err != nil {
		return nil, fmt.Errorf("error preparing query GetProduct: %w", err)
	}
	if q.getProductBySlugStmt, err = db.PrepareContext(ctx, getProductBySlug); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductBySlug: %w", err)
	}
	if q.getProductInventoryStmt, err = db.PrepareContext(ctx, getProductInventory); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductInventory: %w", err)
	}
	if q.getProductInventoryByProductIDStmt, err = db.PrepareContext(ctx, getProductInventoryByProductID); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductInventoryByProductID: %w", err)
	}
	if q.getProductVariantStmt, err = db.PrepareContext(ctx, getProductVariant); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductVariant: %w", err)
	}
	if q.getProductVariantItemStmt, err = db.PrepareContext(ctx, getProductVariantItem); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductVariantItem: %w", err)
	}
	if q.getProductWithVariantsStmt, err = db.PrepareContext(ctx, getProductWithVariants); err != nil {
		return nil, fmt.Errorf("error preparing query GetProductWithVariants: %w", err)
	}
	if q.getVendorStmt, err = db.PrepareContext(ctx, getVendor); err != nil {
		return nil, fmt.Errorf("error preparing query GetVendor: %w", err)
	}
	if q.getVendorUserStmt, err = db.PrepareContext(ctx, getVendorUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetVendorUser: %w", err)
	}
	if q.getZoneStmt, err = db.PrepareContext(ctx, getZone); err != nil {
		return nil, fmt.Errorf("error preparing query GetZone: %w", err)
	}
	if q.listBrandCategoriesStmt, err = db.PrepareContext(ctx, listBrandCategories); err != nil {
		return nil, fmt.Errorf("error preparing query ListBrandCategories: %w", err)
	}
	if q.listBrandZonesStmt, err = db.PrepareContext(ctx, listBrandZones); err != nil {
		return nil, fmt.Errorf("error preparing query ListBrandZones: %w", err)
	}
	if q.listBrandsStmt, err = db.PrepareContext(ctx, listBrands); err != nil {
		return nil, fmt.Errorf("error preparing query ListBrands: %w", err)
	}
	if q.listBrandsByVendorIDStmt, err = db.PrepareContext(ctx, listBrandsByVendorID); err != nil {
		return nil, fmt.Errorf("error preparing query ListBrandsByVendorID: %w", err)
	}
	if q.listCategoriesStmt, err = db.PrepareContext(ctx, listCategories); err != nil {
		return nil, fmt.Errorf("error preparing query ListCategories: %w", err)
	}
	if q.listInventoryHistoryStmt, err = db.PrepareContext(ctx, listInventoryHistory); err != nil {
		return nil, fmt.Errorf("error preparing query ListInventoryHistory: %w", err)
	}
	if q.listOperationTimesByBrandIdStmt, err = db.PrepareContext(ctx, listOperationTimesByBrandId); err != nil {
		return nil, fmt.Errorf("error preparing query ListOperationTimesByBrandId: %w", err)
	}
	if q.listProductInventoryStmt, err = db.PrepareContext(ctx, listProductInventory); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductInventory: %w", err)
	}
	if q.listProductVariantItemsStmt, err = db.PrepareContext(ctx, listProductVariantItems); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductVariantItems: %w", err)
	}
	if q.listProductVariantsStmt, err = db.PrepareContext(ctx, listProductVariants); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductVariants: %w", err)
	}
	if q.listProductsStmt, err = db.PrepareContext(ctx, listProducts); err != nil {
		return nil, fmt.Errorf("error preparing query ListProducts: %w", err)
	}
	if q.listProductsByBrandIDStmt, err = db.PrepareContext(ctx, listProductsByBrandID); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductsByBrandID: %w", err)
	}
	if q.listProductsByCategoryIDStmt, err = db.PrepareContext(ctx, listProductsByCategoryID); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductsByCategoryID: %w", err)
	}
	if q.listProductsByVendorIDStmt, err = db.PrepareContext(ctx, listProductsByVendorID); err != nil {
		return nil, fmt.Errorf("error preparing query ListProductsByVendorID: %w", err)
	}
	if q.listVendorUsersStmt, err = db.PrepareContext(ctx, listVendorUsers); err != nil {
		return nil, fmt.Errorf("error preparing query ListVendorUsers: %w", err)
	}
	if q.listVendorsStmt, err = db.PrepareContext(ctx, listVendors); err != nil {
		return nil, fmt.Errorf("error preparing query ListVendors: %w", err)
	}
	if q.listZonesStmt, err = db.PrepareContext(ctx, listZones); err != nil {
		return nil, fmt.Errorf("error preparing query ListZones: %w", err)
	}
	if q.listZonesByBrandIDStmt, err = db.PrepareContext(ctx, listZonesByBrandID); err != nil {
		return nil, fmt.Errorf("error preparing query ListZonesByBrandID: %w", err)
	}
	if q.searchBrandCategoriesStmt, err = db.PrepareContext(ctx, searchBrandCategories); err != nil {
		return nil, fmt.Errorf("error preparing query SearchBrandCategories: %w", err)
	}
	if q.searchCategoriesStmt, err = db.PrepareContext(ctx, searchCategories); err != nil {
		return nil, fmt.Errorf("error preparing query SearchCategories: %w", err)
	}
	if q.searchInventoryHistoryStmt, err = db.PrepareContext(ctx, searchInventoryHistory); err != nil {
		return nil, fmt.Errorf("error preparing query SearchInventoryHistory: %w", err)
	}
	if q.searchProductInventoryStmt, err = db.PrepareContext(ctx, searchProductInventory); err != nil {
		return nil, fmt.Errorf("error preparing query SearchProductInventory: %w", err)
	}
	if q.searchProductsStmt, err = db.PrepareContext(ctx, searchProducts); err != nil {
		return nil, fmt.Errorf("error preparing query SearchProducts: %w", err)
	}
	if q.searchProductsByBrandIDStmt, err = db.PrepareContext(ctx, searchProductsByBrandID); err != nil {
		return nil, fmt.Errorf("error preparing query SearchProductsByBrandID: %w", err)
	}
	if q.searchProductsByCategoryIDStmt, err = db.PrepareContext(ctx, searchProductsByCategoryID); err != nil {
		return nil, fmt.Errorf("error preparing query SearchProductsByCategoryID: %w", err)
	}
	if q.searchVendorsStmt, err = db.PrepareContext(ctx, searchVendors); err != nil {
		return nil, fmt.Errorf("error preparing query SearchVendors: %w", err)
	}
	if q.searchZonesStmt, err = db.PrepareContext(ctx, searchZones); err != nil {
		return nil, fmt.Errorf("error preparing query SearchZones: %w", err)
	}
	if q.searchZonesByBrandIDStmt, err = db.PrepareContext(ctx, searchZonesByBrandID); err != nil {
		return nil, fmt.Errorf("error preparing query SearchZonesByBrandID: %w", err)
	}
	if q.searchZonesByGeoPointStmt, err = db.PrepareContext(ctx, searchZonesByGeoPoint); err != nil {
		return nil, fmt.Errorf("error preparing query SearchZonesByGeoPoint: %w", err)
	}
	if q.searchZonesByGeoPointAndBrandIDStmt, err = db.PrepareContext(ctx, searchZonesByGeoPointAndBrandID); err != nil {
		return nil, fmt.Errorf("error preparing query SearchZonesByGeoPointAndBrandID: %w", err)
	}
	if q.searchZonesByGeoPolygonStmt, err = db.PrepareContext(ctx, searchZonesByGeoPolygon); err != nil {
		return nil, fmt.Errorf("error preparing query SearchZonesByGeoPolygon: %w", err)
	}
	if q.searchZonesByGeoPolygonAndBrandIDStmt, err = db.PrepareContext(ctx, searchZonesByGeoPolygonAndBrandID); err != nil {
		return nil, fmt.Errorf("error preparing query SearchZonesByGeoPolygonAndBrandID: %w", err)
	}
	if q.updateBrandStmt, err = db.PrepareContext(ctx, updateBrand); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBrand: %w", err)
	}
	if q.updateBrandCategoryStmt, err = db.PrepareContext(ctx, updateBrandCategory); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateBrandCategory: %w", err)
	}
	if q.updateCategoryStmt, err = db.PrepareContext(ctx, updateCategory); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateCategory: %w", err)
	}
	if q.updateInventoryHistoryStmt, err = db.PrepareContext(ctx, updateInventoryHistory); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateInventoryHistory: %w", err)
	}
	if q.updateOperationTimeStmt, err = db.PrepareContext(ctx, updateOperationTime); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateOperationTime: %w", err)
	}
	if q.updateProductStmt, err = db.PrepareContext(ctx, updateProduct); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProduct: %w", err)
	}
	if q.updateProductInventoryStmt, err = db.PrepareContext(ctx, updateProductInventory); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProductInventory: %w", err)
	}
	if q.updateProductVariantStmt, err = db.PrepareContext(ctx, updateProductVariant); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProductVariant: %w", err)
	}
	if q.updateVendorStmt, err = db.PrepareContext(ctx, updateVendor); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateVendor: %w", err)
	}
	if q.updateVendorUserStmt, err = db.PrepareContext(ctx, updateVendorUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateVendorUser: %w", err)
	}
	if q.updateZoneStmt, err = db.PrepareContext(ctx, updateZone); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateZone: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countCategoriesStmt != nil {
		if cerr := q.countCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countCategoriesStmt: %w", cerr)
		}
	}
	if q.countCategoriesByBrandIDStmt != nil {
		if cerr := q.countCategoriesByBrandIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countCategoriesByBrandIDStmt: %w", cerr)
		}
	}
	if q.countInventoryHistoryStmt != nil {
		if cerr := q.countInventoryHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countInventoryHistoryStmt: %w", cerr)
		}
	}
	if q.countInventoryHistoryByProductIdStmt != nil {
		if cerr := q.countInventoryHistoryByProductIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countInventoryHistoryByProductIdStmt: %w", cerr)
		}
	}
	if q.countProductInventoryStmt != nil {
		if cerr := q.countProductInventoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProductInventoryStmt: %w", cerr)
		}
	}
	if q.countProductInventoryByProductIdStmt != nil {
		if cerr := q.countProductInventoryByProductIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProductInventoryByProductIdStmt: %w", cerr)
		}
	}
	if q.countProductVariantItemsStmt != nil {
		if cerr := q.countProductVariantItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProductVariantItemsStmt: %w", cerr)
		}
	}
	if q.countProductVariantsStmt != nil {
		if cerr := q.countProductVariantsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProductVariantsStmt: %w", cerr)
		}
	}
	if q.countProductsStmt != nil {
		if cerr := q.countProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProductsStmt: %w", cerr)
		}
	}
	if q.countProductsByBrandIDStmt != nil {
		if cerr := q.countProductsByBrandIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProductsByBrandIDStmt: %w", cerr)
		}
	}
	if q.countProductsByCategoryIDStmt != nil {
		if cerr := q.countProductsByCategoryIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProductsByCategoryIDStmt: %w", cerr)
		}
	}
	if q.countProductsByVendorIDStmt != nil {
		if cerr := q.countProductsByVendorIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countProductsByVendorIDStmt: %w", cerr)
		}
	}
	if q.countVendorsStmt != nil {
		if cerr := q.countVendorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countVendorsStmt: %w", cerr)
		}
	}
	if q.countZonesStmt != nil {
		if cerr := q.countZonesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countZonesStmt: %w", cerr)
		}
	}
	if q.countZonesByBrandIDStmt != nil {
		if cerr := q.countZonesByBrandIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countZonesByBrandIDStmt: %w", cerr)
		}
	}
	if q.createBrandStmt != nil {
		if cerr := q.createBrandStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBrandStmt: %w", cerr)
		}
	}
	if q.createBrandCategoryStmt != nil {
		if cerr := q.createBrandCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBrandCategoryStmt: %w", cerr)
		}
	}
	if q.createBrandZoneStmt != nil {
		if cerr := q.createBrandZoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createBrandZoneStmt: %w", cerr)
		}
	}
	if q.createCategoryStmt != nil {
		if cerr := q.createCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCategoryStmt: %w", cerr)
		}
	}
	if q.createInventoryHistoryStmt != nil {
		if cerr := q.createInventoryHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInventoryHistoryStmt: %w", cerr)
		}
	}
	if q.createOperationTimeStmt != nil {
		if cerr := q.createOperationTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createOperationTimeStmt: %w", cerr)
		}
	}
	if q.createProductStmt != nil {
		if cerr := q.createProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductStmt: %w", cerr)
		}
	}
	if q.createProductInventoryStmt != nil {
		if cerr := q.createProductInventoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductInventoryStmt: %w", cerr)
		}
	}
	if q.createProductVariantStmt != nil {
		if cerr := q.createProductVariantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductVariantStmt: %w", cerr)
		}
	}
	if q.createProductVariantItemStmt != nil {
		if cerr := q.createProductVariantItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProductVariantItemStmt: %w", cerr)
		}
	}
	if q.createVendorStmt != nil {
		if cerr := q.createVendorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createVendorStmt: %w", cerr)
		}
	}
	if q.createVendorUserStmt != nil {
		if cerr := q.createVendorUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createVendorUserStmt: %w", cerr)
		}
	}
	if q.createZoneStmt != nil {
		if cerr := q.createZoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createZoneStmt: %w", cerr)
		}
	}
	if q.deleteBrandStmt != nil {
		if cerr := q.deleteBrandStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBrandStmt: %w", cerr)
		}
	}
	if q.deleteBrandCategoryStmt != nil {
		if cerr := q.deleteBrandCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBrandCategoryStmt: %w", cerr)
		}
	}
	if q.deleteBrandZoneStmt != nil {
		if cerr := q.deleteBrandZoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteBrandZoneStmt: %w", cerr)
		}
	}
	if q.deleteCategoryStmt != nil {
		if cerr := q.deleteCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteCategoryStmt: %w", cerr)
		}
	}
	if q.deleteInventoryHistoryStmt != nil {
		if cerr := q.deleteInventoryHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteInventoryHistoryStmt: %w", cerr)
		}
	}
	if q.deleteOperationTimeStmt != nil {
		if cerr := q.deleteOperationTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteOperationTimeStmt: %w", cerr)
		}
	}
	if q.deleteProductStmt != nil {
		if cerr := q.deleteProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductStmt: %w", cerr)
		}
	}
	if q.deleteProductInventoryStmt != nil {
		if cerr := q.deleteProductInventoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductInventoryStmt: %w", cerr)
		}
	}
	if q.deleteProductVariantStmt != nil {
		if cerr := q.deleteProductVariantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductVariantStmt: %w", cerr)
		}
	}
	if q.deleteProductVariantItemStmt != nil {
		if cerr := q.deleteProductVariantItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteProductVariantItemStmt: %w", cerr)
		}
	}
	if q.deleteVendorStmt != nil {
		if cerr := q.deleteVendorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteVendorStmt: %w", cerr)
		}
	}
	if q.deleteVendorUserStmt != nil {
		if cerr := q.deleteVendorUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteVendorUserStmt: %w", cerr)
		}
	}
	if q.deleteZoneStmt != nil {
		if cerr := q.deleteZoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteZoneStmt: %w", cerr)
		}
	}
	if q.getBrandStmt != nil {
		if cerr := q.getBrandStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBrandStmt: %w", cerr)
		}
	}
	if q.getBrandCategoryStmt != nil {
		if cerr := q.getBrandCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getBrandCategoryStmt: %w", cerr)
		}
	}
	if q.getCategoryStmt != nil {
		if cerr := q.getCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getCategoryStmt: %w", cerr)
		}
	}
	if q.getInventoryHistoryStmt != nil {
		if cerr := q.getInventoryHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInventoryHistoryStmt: %w", cerr)
		}
	}
	if q.getInventoryHistoryByProductIDStmt != nil {
		if cerr := q.getInventoryHistoryByProductIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getInventoryHistoryByProductIDStmt: %w", cerr)
		}
	}
	if q.getOperationTimeStmt != nil {
		if cerr := q.getOperationTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getOperationTimeStmt: %w", cerr)
		}
	}
	if q.getProductStmt != nil {
		if cerr := q.getProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductStmt: %w", cerr)
		}
	}
	if q.getProductBySlugStmt != nil {
		if cerr := q.getProductBySlugStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductBySlugStmt: %w", cerr)
		}
	}
	if q.getProductInventoryStmt != nil {
		if cerr := q.getProductInventoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductInventoryStmt: %w", cerr)
		}
	}
	if q.getProductInventoryByProductIDStmt != nil {
		if cerr := q.getProductInventoryByProductIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductInventoryByProductIDStmt: %w", cerr)
		}
	}
	if q.getProductVariantStmt != nil {
		if cerr := q.getProductVariantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductVariantStmt: %w", cerr)
		}
	}
	if q.getProductVariantItemStmt != nil {
		if cerr := q.getProductVariantItemStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductVariantItemStmt: %w", cerr)
		}
	}
	if q.getProductWithVariantsStmt != nil {
		if cerr := q.getProductWithVariantsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getProductWithVariantsStmt: %w", cerr)
		}
	}
	if q.getVendorStmt != nil {
		if cerr := q.getVendorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVendorStmt: %w", cerr)
		}
	}
	if q.getVendorUserStmt != nil {
		if cerr := q.getVendorUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVendorUserStmt: %w", cerr)
		}
	}
	if q.getZoneStmt != nil {
		if cerr := q.getZoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getZoneStmt: %w", cerr)
		}
	}
	if q.listBrandCategoriesStmt != nil {
		if cerr := q.listBrandCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBrandCategoriesStmt: %w", cerr)
		}
	}
	if q.listBrandZonesStmt != nil {
		if cerr := q.listBrandZonesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBrandZonesStmt: %w", cerr)
		}
	}
	if q.listBrandsStmt != nil {
		if cerr := q.listBrandsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBrandsStmt: %w", cerr)
		}
	}
	if q.listBrandsByVendorIDStmt != nil {
		if cerr := q.listBrandsByVendorIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listBrandsByVendorIDStmt: %w", cerr)
		}
	}
	if q.listCategoriesStmt != nil {
		if cerr := q.listCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCategoriesStmt: %w", cerr)
		}
	}
	if q.listInventoryHistoryStmt != nil {
		if cerr := q.listInventoryHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listInventoryHistoryStmt: %w", cerr)
		}
	}
	if q.listOperationTimesByBrandIdStmt != nil {
		if cerr := q.listOperationTimesByBrandIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listOperationTimesByBrandIdStmt: %w", cerr)
		}
	}
	if q.listProductInventoryStmt != nil {
		if cerr := q.listProductInventoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductInventoryStmt: %w", cerr)
		}
	}
	if q.listProductVariantItemsStmt != nil {
		if cerr := q.listProductVariantItemsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductVariantItemsStmt: %w", cerr)
		}
	}
	if q.listProductVariantsStmt != nil {
		if cerr := q.listProductVariantsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductVariantsStmt: %w", cerr)
		}
	}
	if q.listProductsStmt != nil {
		if cerr := q.listProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsStmt: %w", cerr)
		}
	}
	if q.listProductsByBrandIDStmt != nil {
		if cerr := q.listProductsByBrandIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsByBrandIDStmt: %w", cerr)
		}
	}
	if q.listProductsByCategoryIDStmt != nil {
		if cerr := q.listProductsByCategoryIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsByCategoryIDStmt: %w", cerr)
		}
	}
	if q.listProductsByVendorIDStmt != nil {
		if cerr := q.listProductsByVendorIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProductsByVendorIDStmt: %w", cerr)
		}
	}
	if q.listVendorUsersStmt != nil {
		if cerr := q.listVendorUsersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listVendorUsersStmt: %w", cerr)
		}
	}
	if q.listVendorsStmt != nil {
		if cerr := q.listVendorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listVendorsStmt: %w", cerr)
		}
	}
	if q.listZonesStmt != nil {
		if cerr := q.listZonesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listZonesStmt: %w", cerr)
		}
	}
	if q.listZonesByBrandIDStmt != nil {
		if cerr := q.listZonesByBrandIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listZonesByBrandIDStmt: %w", cerr)
		}
	}
	if q.searchBrandCategoriesStmt != nil {
		if cerr := q.searchBrandCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchBrandCategoriesStmt: %w", cerr)
		}
	}
	if q.searchCategoriesStmt != nil {
		if cerr := q.searchCategoriesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchCategoriesStmt: %w", cerr)
		}
	}
	if q.searchInventoryHistoryStmt != nil {
		if cerr := q.searchInventoryHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchInventoryHistoryStmt: %w", cerr)
		}
	}
	if q.searchProductInventoryStmt != nil {
		if cerr := q.searchProductInventoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchProductInventoryStmt: %w", cerr)
		}
	}
	if q.searchProductsStmt != nil {
		if cerr := q.searchProductsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchProductsStmt: %w", cerr)
		}
	}
	if q.searchProductsByBrandIDStmt != nil {
		if cerr := q.searchProductsByBrandIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchProductsByBrandIDStmt: %w", cerr)
		}
	}
	if q.searchProductsByCategoryIDStmt != nil {
		if cerr := q.searchProductsByCategoryIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchProductsByCategoryIDStmt: %w", cerr)
		}
	}
	if q.searchVendorsStmt != nil {
		if cerr := q.searchVendorsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchVendorsStmt: %w", cerr)
		}
	}
	if q.searchZonesStmt != nil {
		if cerr := q.searchZonesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchZonesStmt: %w", cerr)
		}
	}
	if q.searchZonesByBrandIDStmt != nil {
		if cerr := q.searchZonesByBrandIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchZonesByBrandIDStmt: %w", cerr)
		}
	}
	if q.searchZonesByGeoPointStmt != nil {
		if cerr := q.searchZonesByGeoPointStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchZonesByGeoPointStmt: %w", cerr)
		}
	}
	if q.searchZonesByGeoPointAndBrandIDStmt != nil {
		if cerr := q.searchZonesByGeoPointAndBrandIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchZonesByGeoPointAndBrandIDStmt: %w", cerr)
		}
	}
	if q.searchZonesByGeoPolygonStmt != nil {
		if cerr := q.searchZonesByGeoPolygonStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchZonesByGeoPolygonStmt: %w", cerr)
		}
	}
	if q.searchZonesByGeoPolygonAndBrandIDStmt != nil {
		if cerr := q.searchZonesByGeoPolygonAndBrandIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchZonesByGeoPolygonAndBrandIDStmt: %w", cerr)
		}
	}
	if q.updateBrandStmt != nil {
		if cerr := q.updateBrandStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBrandStmt: %w", cerr)
		}
	}
	if q.updateBrandCategoryStmt != nil {
		if cerr := q.updateBrandCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateBrandCategoryStmt: %w", cerr)
		}
	}
	if q.updateCategoryStmt != nil {
		if cerr := q.updateCategoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateCategoryStmt: %w", cerr)
		}
	}
	if q.updateInventoryHistoryStmt != nil {
		if cerr := q.updateInventoryHistoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateInventoryHistoryStmt: %w", cerr)
		}
	}
	if q.updateOperationTimeStmt != nil {
		if cerr := q.updateOperationTimeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateOperationTimeStmt: %w", cerr)
		}
	}
	if q.updateProductStmt != nil {
		if cerr := q.updateProductStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductStmt: %w", cerr)
		}
	}
	if q.updateProductInventoryStmt != nil {
		if cerr := q.updateProductInventoryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductInventoryStmt: %w", cerr)
		}
	}
	if q.updateProductVariantStmt != nil {
		if cerr := q.updateProductVariantStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProductVariantStmt: %w", cerr)
		}
	}
	if q.updateVendorStmt != nil {
		if cerr := q.updateVendorStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateVendorStmt: %w", cerr)
		}
	}
	if q.updateVendorUserStmt != nil {
		if cerr := q.updateVendorUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateVendorUserStmt: %w", cerr)
		}
	}
	if q.updateZoneStmt != nil {
		if cerr := q.updateZoneStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateZoneStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                    DBTX
	tx                                    *sql.Tx
	countCategoriesStmt                   *sql.Stmt
	countCategoriesByBrandIDStmt          *sql.Stmt
	countInventoryHistoryStmt             *sql.Stmt
	countInventoryHistoryByProductIdStmt  *sql.Stmt
	countProductInventoryStmt             *sql.Stmt
	countProductInventoryByProductIdStmt  *sql.Stmt
	countProductVariantItemsStmt          *sql.Stmt
	countProductVariantsStmt              *sql.Stmt
	countProductsStmt                     *sql.Stmt
	countProductsByBrandIDStmt            *sql.Stmt
	countProductsByCategoryIDStmt         *sql.Stmt
	countProductsByVendorIDStmt           *sql.Stmt
	countVendorsStmt                      *sql.Stmt
	countZonesStmt                        *sql.Stmt
	countZonesByBrandIDStmt               *sql.Stmt
	createBrandStmt                       *sql.Stmt
	createBrandCategoryStmt               *sql.Stmt
	createBrandZoneStmt                   *sql.Stmt
	createCategoryStmt                    *sql.Stmt
	createInventoryHistoryStmt            *sql.Stmt
	createOperationTimeStmt               *sql.Stmt
	createProductStmt                     *sql.Stmt
	createProductInventoryStmt            *sql.Stmt
	createProductVariantStmt              *sql.Stmt
	createProductVariantItemStmt          *sql.Stmt
	createVendorStmt                      *sql.Stmt
	createVendorUserStmt                  *sql.Stmt
	createZoneStmt                        *sql.Stmt
	deleteBrandStmt                       *sql.Stmt
	deleteBrandCategoryStmt               *sql.Stmt
	deleteBrandZoneStmt                   *sql.Stmt
	deleteCategoryStmt                    *sql.Stmt
	deleteInventoryHistoryStmt            *sql.Stmt
	deleteOperationTimeStmt               *sql.Stmt
	deleteProductStmt                     *sql.Stmt
	deleteProductInventoryStmt            *sql.Stmt
	deleteProductVariantStmt              *sql.Stmt
	deleteProductVariantItemStmt          *sql.Stmt
	deleteVendorStmt                      *sql.Stmt
	deleteVendorUserStmt                  *sql.Stmt
	deleteZoneStmt                        *sql.Stmt
	getBrandStmt                          *sql.Stmt
	getBrandCategoryStmt                  *sql.Stmt
	getCategoryStmt                       *sql.Stmt
	getInventoryHistoryStmt               *sql.Stmt
	getInventoryHistoryByProductIDStmt    *sql.Stmt
	getOperationTimeStmt                  *sql.Stmt
	getProductStmt                        *sql.Stmt
	getProductBySlugStmt                  *sql.Stmt
	getProductInventoryStmt               *sql.Stmt
	getProductInventoryByProductIDStmt    *sql.Stmt
	getProductVariantStmt                 *sql.Stmt
	getProductVariantItemStmt             *sql.Stmt
	getProductWithVariantsStmt            *sql.Stmt
	getVendorStmt                         *sql.Stmt
	getVendorUserStmt                     *sql.Stmt
	getZoneStmt                           *sql.Stmt
	listBrandCategoriesStmt               *sql.Stmt
	listBrandZonesStmt                    *sql.Stmt
	listBrandsStmt                        *sql.Stmt
	listBrandsByVendorIDStmt              *sql.Stmt
	listCategoriesStmt                    *sql.Stmt
	listInventoryHistoryStmt              *sql.Stmt
	listOperationTimesByBrandIdStmt       *sql.Stmt
	listProductInventoryStmt              *sql.Stmt
	listProductVariantItemsStmt           *sql.Stmt
	listProductVariantsStmt               *sql.Stmt
	listProductsStmt                      *sql.Stmt
	listProductsByBrandIDStmt             *sql.Stmt
	listProductsByCategoryIDStmt          *sql.Stmt
	listProductsByVendorIDStmt            *sql.Stmt
	listVendorUsersStmt                   *sql.Stmt
	listVendorsStmt                       *sql.Stmt
	listZonesStmt                         *sql.Stmt
	listZonesByBrandIDStmt                *sql.Stmt
	searchBrandCategoriesStmt             *sql.Stmt
	searchCategoriesStmt                  *sql.Stmt
	searchInventoryHistoryStmt            *sql.Stmt
	searchProductInventoryStmt            *sql.Stmt
	searchProductsStmt                    *sql.Stmt
	searchProductsByBrandIDStmt           *sql.Stmt
	searchProductsByCategoryIDStmt        *sql.Stmt
	searchVendorsStmt                     *sql.Stmt
	searchZonesStmt                       *sql.Stmt
	searchZonesByBrandIDStmt              *sql.Stmt
	searchZonesByGeoPointStmt             *sql.Stmt
	searchZonesByGeoPointAndBrandIDStmt   *sql.Stmt
	searchZonesByGeoPolygonStmt           *sql.Stmt
	searchZonesByGeoPolygonAndBrandIDStmt *sql.Stmt
	updateBrandStmt                       *sql.Stmt
	updateBrandCategoryStmt               *sql.Stmt
	updateCategoryStmt                    *sql.Stmt
	updateInventoryHistoryStmt            *sql.Stmt
	updateOperationTimeStmt               *sql.Stmt
	updateProductStmt                     *sql.Stmt
	updateProductInventoryStmt            *sql.Stmt
	updateProductVariantStmt              *sql.Stmt
	updateVendorStmt                      *sql.Stmt
	updateVendorUserStmt                  *sql.Stmt
	updateZoneStmt                        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                    tx,
		tx:                                    tx,
		countCategoriesStmt:                   q.countCategoriesStmt,
		countCategoriesByBrandIDStmt:          q.countCategoriesByBrandIDStmt,
		countInventoryHistoryStmt:             q.countInventoryHistoryStmt,
		countInventoryHistoryByProductIdStmt:  q.countInventoryHistoryByProductIdStmt,
		countProductInventoryStmt:             q.countProductInventoryStmt,
		countProductInventoryByProductIdStmt:  q.countProductInventoryByProductIdStmt,
		countProductVariantItemsStmt:          q.countProductVariantItemsStmt,
		countProductVariantsStmt:              q.countProductVariantsStmt,
		countProductsStmt:                     q.countProductsStmt,
		countProductsByBrandIDStmt:            q.countProductsByBrandIDStmt,
		countProductsByCategoryIDStmt:         q.countProductsByCategoryIDStmt,
		countProductsByVendorIDStmt:           q.countProductsByVendorIDStmt,
		countVendorsStmt:                      q.countVendorsStmt,
		countZonesStmt:                        q.countZonesStmt,
		countZonesByBrandIDStmt:               q.countZonesByBrandIDStmt,
		createBrandStmt:                       q.createBrandStmt,
		createBrandCategoryStmt:               q.createBrandCategoryStmt,
		createBrandZoneStmt:                   q.createBrandZoneStmt,
		createCategoryStmt:                    q.createCategoryStmt,
		createInventoryHistoryStmt:            q.createInventoryHistoryStmt,
		createOperationTimeStmt:               q.createOperationTimeStmt,
		createProductStmt:                     q.createProductStmt,
		createProductInventoryStmt:            q.createProductInventoryStmt,
		createProductVariantStmt:              q.createProductVariantStmt,
		createProductVariantItemStmt:          q.createProductVariantItemStmt,
		createVendorStmt:                      q.createVendorStmt,
		createVendorUserStmt:                  q.createVendorUserStmt,
		createZoneStmt:                        q.createZoneStmt,
		deleteBrandStmt:                       q.deleteBrandStmt,
		deleteBrandCategoryStmt:               q.deleteBrandCategoryStmt,
		deleteBrandZoneStmt:                   q.deleteBrandZoneStmt,
		deleteCategoryStmt:                    q.deleteCategoryStmt,
		deleteInventoryHistoryStmt:            q.deleteInventoryHistoryStmt,
		deleteOperationTimeStmt:               q.deleteOperationTimeStmt,
		deleteProductStmt:                     q.deleteProductStmt,
		deleteProductInventoryStmt:            q.deleteProductInventoryStmt,
		deleteProductVariantStmt:              q.deleteProductVariantStmt,
		deleteProductVariantItemStmt:          q.deleteProductVariantItemStmt,
		deleteVendorStmt:                      q.deleteVendorStmt,
		deleteVendorUserStmt:                  q.deleteVendorUserStmt,
		deleteZoneStmt:                        q.deleteZoneStmt,
		getBrandStmt:                          q.getBrandStmt,
		getBrandCategoryStmt:                  q.getBrandCategoryStmt,
		getCategoryStmt:                       q.getCategoryStmt,
		getInventoryHistoryStmt:               q.getInventoryHistoryStmt,
		getInventoryHistoryByProductIDStmt:    q.getInventoryHistoryByProductIDStmt,
		getOperationTimeStmt:                  q.getOperationTimeStmt,
		getProductStmt:                        q.getProductStmt,
		getProductBySlugStmt:                  q.getProductBySlugStmt,
		getProductInventoryStmt:               q.getProductInventoryStmt,
		getProductInventoryByProductIDStmt:    q.getProductInventoryByProductIDStmt,
		getProductVariantStmt:                 q.getProductVariantStmt,
		getProductVariantItemStmt:             q.getProductVariantItemStmt,
		getProductWithVariantsStmt:            q.getProductWithVariantsStmt,
		getVendorStmt:                         q.getVendorStmt,
		getVendorUserStmt:                     q.getVendorUserStmt,
		getZoneStmt:                           q.getZoneStmt,
		listBrandCategoriesStmt:               q.listBrandCategoriesStmt,
		listBrandZonesStmt:                    q.listBrandZonesStmt,
		listBrandsStmt:                        q.listBrandsStmt,
		listBrandsByVendorIDStmt:              q.listBrandsByVendorIDStmt,
		listCategoriesStmt:                    q.listCategoriesStmt,
		listInventoryHistoryStmt:              q.listInventoryHistoryStmt,
		listOperationTimesByBrandIdStmt:       q.listOperationTimesByBrandIdStmt,
		listProductInventoryStmt:              q.listProductInventoryStmt,
		listProductVariantItemsStmt:           q.listProductVariantItemsStmt,
		listProductVariantsStmt:               q.listProductVariantsStmt,
		listProductsStmt:                      q.listProductsStmt,
		listProductsByBrandIDStmt:             q.listProductsByBrandIDStmt,
		listProductsByCategoryIDStmt:          q.listProductsByCategoryIDStmt,
		listProductsByVendorIDStmt:            q.listProductsByVendorIDStmt,
		listVendorUsersStmt:                   q.listVendorUsersStmt,
		listVendorsStmt:                       q.listVendorsStmt,
		listZonesStmt:                         q.listZonesStmt,
		listZonesByBrandIDStmt:                q.listZonesByBrandIDStmt,
		searchBrandCategoriesStmt:             q.searchBrandCategoriesStmt,
		searchCategoriesStmt:                  q.searchCategoriesStmt,
		searchInventoryHistoryStmt:            q.searchInventoryHistoryStmt,
		searchProductInventoryStmt:            q.searchProductInventoryStmt,
		searchProductsStmt:                    q.searchProductsStmt,
		searchProductsByBrandIDStmt:           q.searchProductsByBrandIDStmt,
		searchProductsByCategoryIDStmt:        q.searchProductsByCategoryIDStmt,
		searchVendorsStmt:                     q.searchVendorsStmt,
		searchZonesStmt:                       q.searchZonesStmt,
		searchZonesByBrandIDStmt:              q.searchZonesByBrandIDStmt,
		searchZonesByGeoPointStmt:             q.searchZonesByGeoPointStmt,
		searchZonesByGeoPointAndBrandIDStmt:   q.searchZonesByGeoPointAndBrandIDStmt,
		searchZonesByGeoPolygonStmt:           q.searchZonesByGeoPolygonStmt,
		searchZonesByGeoPolygonAndBrandIDStmt: q.searchZonesByGeoPolygonAndBrandIDStmt,
		updateBrandStmt:                       q.updateBrandStmt,
		updateBrandCategoryStmt:               q.updateBrandCategoryStmt,
		updateCategoryStmt:                    q.updateCategoryStmt,
		updateInventoryHistoryStmt:            q.updateInventoryHistoryStmt,
		updateOperationTimeStmt:               q.updateOperationTimeStmt,
		updateProductStmt:                     q.updateProductStmt,
		updateProductInventoryStmt:            q.updateProductInventoryStmt,
		updateProductVariantStmt:              q.updateProductVariantStmt,
		updateVendorStmt:                      q.updateVendorStmt,
		updateVendorUserStmt:                  q.updateVendorUserStmt,
		updateZoneStmt:                        q.updateZoneStmt,
	}
}
