// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"encoding/json"
	"time"
)

type Brand struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	MetaTags      string      `json:"meta_tags"`
	Slug          string      `json:"slug"`
	Type          string      `json:"type"`
	Phone         string      `json:"phone"`
	Email         string      `json:"email"`
	EmailVerified bool        `json:"email_verified"`
	Logo          string      `json:"logo"`
	Banner        string      `json:"banner"`
	Rating        int32       `json:"rating"`
	VendorID      int64       `json:"vendor_id"`
	Prefix        string      `json:"prefix"`
	Status        string      `json:"status"`
	Availability  bool        `json:"availability"`
	Location      interface{} `json:"location"`
	Address       string      `json:"address"`
	CreatedAt     time.Time   `json:"created_at"`
}

type BrandCategory struct {
	ID         int64     `json:"id"`
	BrandID    int64     `json:"brand_id"`
	CategoryID int64     `json:"category_id"`
	Name       string    `json:"name"`
	CreatedAt  time.Time `json:"created_at"`
}

type BrandOrder struct {
	ID       int64   `json:"id"`
	BrandID  int64   `json:"brand_id"`
	OrderID  int64   `json:"order_id"`
	Status   string  `json:"status"`
	Total    float64 `json:"total"`
	Discount float64 `json:"discount"`
	Note     string  `json:"note"`
}

type BrandZone struct {
	ID        int32     `json:"id"`
	BrandID   int64     `json:"brand_id"`
	ZoneID    int64     `json:"zone_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Image     string    `json:"image"`
	CreatedAt time.Time `json:"created_at"`
}

type Customer struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Phone         string    `json:"phone"`
	Email         string    `json:"email"`
	Image         string    `json:"image"`
	EmailVerified bool      `json:"email_verified"`
	Nid           string    `json:"nid"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type CustomerAddress struct {
	ID         int64       `json:"id"`
	CustomerID int64       `json:"customer_id"`
	Label      string      `json:"label"`
	Address    string      `json:"address"`
	GeoPoint   interface{} `json:"geo_point"`
	Apartment  string      `json:"apartment"`
	Area       string      `json:"area"`
	Floor      string      `json:"floor"`
	CreatedAt  time.Time   `json:"created_at"`
}

type DeliveryAddress struct {
	ID         int64       `json:"id"`
	OrderID    int64       `json:"order_id"`
	CustomerID int64       `json:"customer_id"`
	Address    string      `json:"address"`
	GeoPoint   interface{} `json:"geo_point"`
	Apartment  string      `json:"apartment"`
	Area       string      `json:"area"`
	Floor      string      `json:"floor"`
	Phone      string      `json:"phone"`
}

type InventoryHistory struct {
	ID        int64 `json:"id"`
	ProductID int64 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
	// it would be like input, sold, restock, damage etc
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

type OperationTime struct {
	ID        int64     `json:"id"`
	BrandID   int64     `json:"brand_id"`
	DayOfWeek int32     `json:"day_of_week"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	CreatedAt time.Time `json:"created_at"`
}

type Order struct {
	ID            int64     `json:"id"`
	CustomerID    int64     `json:"customer_id"`
	Status        string    `json:"status"`
	PaymentMethod string    `json:"payment_method"`
	PaymentStatus string    `json:"payment_status"`
	RiderNote     string    `json:"rider_note"`
	DispatchTime  time.Time `json:"dispatch_time"`
	Total         float64   `json:"total"`
	TotalDiscount float64   `json:"total_discount"`
	ServiceCharge float64   `json:"service_charge"`
	Payable       float64   `json:"payable"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type OrderItem struct {
	ID        int64     `json:"id"`
	OrderID   int64     `json:"order_id"`
	ProductID int64     `json:"product_id"`
	BrandID   int64     `json:"brand_id"`
	Price     float64   `json:"price"`
	Quantity  int32     `json:"quantity"`
	Discount  float64   `json:"discount"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type OrderLog struct {
	ID           int64           `json:"id"`
	OrderID      int64           `json:"order_id"`
	UserType     string          `json:"user_type"`
	UserName     string          `json:"user_name"`
	UserID       int64           `json:"user_id"`
	ActionType   string          `json:"action_type"`
	PrevValue    json.RawMessage `json:"prev_value"`
	CurrentValue json.RawMessage `json:"current_value"`
	Message      string          `json:"message"`
	CreatedAt    time.Time       `json:"created_at"`
}

type Product struct {
	ID           int64     `json:"id"`
	Type         string    `json:"type"`
	Name         string    `json:"name"`
	CategoryID   int64     `json:"category_id"`
	Slug         string    `json:"slug"`
	Image        string    `json:"image"`
	Details      string    `json:"details"`
	Price        float64   `json:"price"`
	Status       string    `json:"status"`
	BrandID      int64     `json:"brand_id"`
	Availability bool      `json:"availability"`
	UseInventory bool      `json:"use_inventory"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ProductInventory struct {
	ID            int64     `json:"id"`
	ProductID     int64     `json:"product_id"`
	Quantity      int32     `json:"quantity"`
	PurchasePrice float64   `json:"purchase_price"`
	SellingPrice  float64   `json:"selling_price"`
	ExpireDate    time.Time `json:"expire_date"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ProductVariant struct {
	ID        int64     `json:"id"`
	ProductID int64     `json:"product_id"`
	Title     string    `json:"title"`
	MinSelect int32     `json:"min_select"`
	MaxSelect int32     `json:"max_select"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProductVariantItem struct {
	ID        int64     `json:"id"`
	VariantID int64     `json:"variant_id"`
	ProductID int64     `json:"product_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Rider struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	Phone          string `json:"phone"`
	HashedPassword string `json:"hashed_password"`
}

type RiderAssign struct {
	ID        int64     `json:"id"`
	OrderID   int64     `json:"order_id"`
	RiderID   int64     `json:"rider_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Vendor struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Email       string          `json:"email"`
	Phone       string          `json:"phone"`
	PaymentInfo json.RawMessage `json:"payment_info"`
	SocialLinks json.RawMessage `json:"social_links"`
	CreatedAt   time.Time       `json:"created_at"`
}

type VendorUser struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	Role              string    `json:"role"`
	VendorID          int64     `json:"vendor_id"`
	CreatedAt         time.Time `json:"created_at"`
}

type Zone struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Boundary  interface{} `json:"boundary"`
	CreatedAt time.Time   `json:"created_at"`
}
