// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Brand struct {
	ID            int64       `json:"id"`
	Name          string      `json:"name"`
	MetaTags      string      `json:"meta_tags"`
	Slug          string      `json:"slug"`
	Type          string      `json:"type"`
	Phone         string      `json:"phone"`
	Email         string      `json:"email"`
	EmailVerified bool        `json:"email_verified"`
	Logo          string      `json:"logo"`
	Banner        string      `json:"banner"`
	Rating        int32       `json:"rating"`
	VendorID      int64       `json:"vendor_id"`
	Prefix        string      `json:"prefix"`
	Status        string      `json:"status"`
	Availability  bool        `json:"availability"`
	Location      interface{} `json:"location"`
	Address       string      `json:"address"`
	CreatedAt     time.Time   `json:"created_at"`
}

type BrandCategory struct {
	ID        int64     `json:"id"`
	BrandID   int64     `json:"brand_id"`
	Name      string    `json:"name"`
	Image     string    `json:"image"`
	CreatedAt time.Time `json:"created_at"`
}

type BrandZone struct {
	ID        int32     `json:"id"`
	BrandID   int32     `json:"brand_id"`
	ZoneID    int32     `json:"zone_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Category struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Image     string    `json:"image"`
	CreatedAt time.Time `json:"created_at"`
}

type InventoryHistory struct {
	ID        int64 `json:"id"`
	ProductID int64 `json:"product_id"`
	Quantity  int32 `json:"quantity"`
	// it would be like input, sold, restock, damage etc
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

type OperationTime struct {
	ID        int64     `json:"id"`
	BrandID   int32     `json:"brand_id"`
	DayOfWeek int32     `json:"day_of_week"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
	CreatedAt time.Time `json:"created_at"`
}

type Product struct {
	ID           int64     `json:"id"`
	Type         string    `json:"type"`
	Name         string    `json:"name"`
	CategoryID   int64     `json:"category_id"`
	Slug         string    `json:"slug"`
	Image        string    `json:"image"`
	Details      string    `json:"details"`
	Price        float64   `json:"price"`
	Status       string    `json:"status"`
	BrandID      int64     `json:"brand_id"`
	Availability bool      `json:"availability"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ProductInventory struct {
	ID            int64     `json:"id"`
	ProductID     int64     `json:"product_id"`
	Quantity      int32     `json:"quantity"`
	PurchasePrice float64   `json:"purchase_price"`
	SellingPrice  float64   `json:"selling_price"`
	ExpireDate    time.Time `json:"expire_date"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type ProductVariant struct {
	ID        int64     `json:"id"`
	ProductID int64     `json:"product_id"`
	Title     string    `json:"title"`
	MinSelect int32     `json:"min_select"`
	MaxSelect int32     `json:"max_select"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProductVariantItem struct {
	ID        int64     `json:"id"`
	VariantID int64     `json:"variant_id"`
	ProductID int64     `json:"product_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Vendor struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Email       string          `json:"email"`
	Phone       string          `json:"phone"`
	PaymentInfo json.RawMessage `json:"payment_info"`
	SocialLinks json.RawMessage `json:"social_links"`
	CreatedAt   time.Time       `json:"created_at"`
}

type VendorPermission struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	CreatedAt time.Time      `json:"created_at"`
}

type VendorUser struct {
	ID                int32          `json:"id"`
	Username          sql.NullString `json:"username"`
	FullName          string         `json:"full_name"`
	Email             string         `json:"email"`
	HashedPassword    string         `json:"hashed_password"`
	PasswordChangedAt time.Time      `json:"password_changed_at"`
	Role              string         `json:"role"`
	VendorID          int32          `json:"vendor_id"`
	CreatedAt         time.Time      `json:"created_at"`
}

type VendorUserPermission struct {
	ID           int64     `json:"id"`
	UserID       int32     `json:"user_id"`
	PermissionID int32     `json:"permission_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type Zone struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	Boundary  interface{}    `json:"boundary"`
	CreatedAt time.Time      `json:"created_at"`
}
