// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"context"
)

type Querier interface {
	CountCategories(ctx context.Context) (int64, error)
	CountCategoriesByBrandID(ctx context.Context, brandID int64) (int64, error)
	CountInventoryHistory(ctx context.Context, productID int64) (int64, error)
	CountInventoryHistoryByProductId(ctx context.Context, productID int64) (int64, error)
	CountProductInventory(ctx context.Context, productID int64) (int64, error)
	CountProductInventoryByProductId(ctx context.Context, productID int64) (int64, error)
	CountProductVariantItems(ctx context.Context, variantID int64) (int64, error)
	CountProductVariants(ctx context.Context, productID int64) (int64, error)
	CountProducts(ctx context.Context) (int64, error)
	CountProductsByBrandID(ctx context.Context, brandID int64) (int64, error)
	CountProductsByCategoryID(ctx context.Context, categoryID int64) (int64, error)
	CountProductsByVendorID(ctx context.Context, id int64) (int64, error)
	CountVendors(ctx context.Context) (int64, error)
	CountZones(ctx context.Context) (int64, error)
	CountZonesByBrandID(ctx context.Context, brandID int64) (int64, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error)
	CreateBrandCategory(ctx context.Context, arg CreateBrandCategoryParams) (BrandCategory, error)
	CreateBrandZone(ctx context.Context, arg CreateBrandZoneParams) (BrandZone, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateInventoryHistory(ctx context.Context, arg CreateInventoryHistoryParams) (InventoryHistory, error)
	CreateOperationTime(ctx context.Context, arg CreateOperationTimeParams) (OperationTime, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductInventory(ctx context.Context, arg CreateProductInventoryParams) (ProductInventory, error)
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreateProductVariantItem(ctx context.Context, arg CreateProductVariantItemParams) (ProductVariantItem, error)
	CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error)
	CreateVendorUser(ctx context.Context, arg CreateVendorUserParams) (VendorUser, error)
	// CREATE TABLE "zones" (
	//   "id" int PRIMARY KEY,
	//   "name" varchar,
	//   "boundary" "geography(Polygon, 4326)",
	//   "created_at" timestamptz NOT NULL DEFAULT (now())
	// );
	// CREATE TABLE "brand_zones" (
	//   "id" int PRIMARY KEY,
	//   "brand_id" int NOT NULL,
	//   "zone_id" int NOT NULL,
	//   "created_at" timestamptz NOT NULL DEFAULT (now())
	// );
	CreateZone(ctx context.Context, arg CreateZoneParams) (Zone, error)
	DeleteBrand(ctx context.Context, id int64) error
	DeleteBrandCategory(ctx context.Context, arg DeleteBrandCategoryParams) error
	DeleteBrandZone(ctx context.Context, arg DeleteBrandZoneParams) error
	DeleteCategory(ctx context.Context, id int64) error
	DeleteInventoryHistory(ctx context.Context, id int64) error
	DeleteOperationTime(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteProductInventory(ctx context.Context, id int64) error
	DeleteProductVariant(ctx context.Context, id int64) error
	DeleteProductVariantItem(ctx context.Context, id int64) error
	DeleteVendor(ctx context.Context, id int64) error
	DeleteVendorUser(ctx context.Context, id int64) error
	DeleteZone(ctx context.Context, id int32) error
	GetBrand(ctx context.Context, id int64) (Brand, error)
	GetBrandCategory(ctx context.Context, arg GetBrandCategoryParams) (BrandCategory, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetInventoryHistory(ctx context.Context, id int64) (InventoryHistory, error)
	GetInventoryHistoryByProductID(ctx context.Context, productID int64) (InventoryHistory, error)
	GetOperationTime(ctx context.Context, id int64) (OperationTime, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductBySlug(ctx context.Context, slug string) (Product, error)
	GetProductInventory(ctx context.Context, id int64) (ProductInventory, error)
	GetProductInventoryByProductID(ctx context.Context, productID int64) (ProductInventory, error)
	GetProductVariant(ctx context.Context, id int64) (ProductVariant, error)
	GetProductVariantItem(ctx context.Context, id int64) (ProductVariantItem, error)
	GetProductWithVariants(ctx context.Context, id int64) (GetProductWithVariantsRow, error)
	GetVendor(ctx context.Context, id int64) (Vendor, error)
	GetVendorUser(ctx context.Context, id int64) (VendorUser, error)
	GetVendorUserByUsername(ctx context.Context, username string) (VendorUser, error)
	GetZone(ctx context.Context, id int32) (Zone, error)
	ListBrandCategories(ctx context.Context, arg ListBrandCategoriesParams) ([]BrandCategory, error)
	ListBrandZones(ctx context.Context, arg ListBrandZonesParams) ([]BrandZone, error)
	ListBrands(ctx context.Context, arg ListBrandsParams) ([]Brand, error)
	ListBrandsByVendorID(ctx context.Context, arg ListBrandsByVendorIDParams) ([]Brand, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListInventoryHistory(ctx context.Context, arg ListInventoryHistoryParams) ([]InventoryHistory, error)
	ListOperationTimesByBrandId(ctx context.Context, arg ListOperationTimesByBrandIdParams) ([]OperationTime, error)
	ListProductInventory(ctx context.Context, arg ListProductInventoryParams) ([]ProductInventory, error)
	ListProductVariantItems(ctx context.Context, arg ListProductVariantItemsParams) ([]ProductVariantItem, error)
	ListProductVariants(ctx context.Context, arg ListProductVariantsParams) ([]ProductVariant, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByBrandID(ctx context.Context, arg ListProductsByBrandIDParams) ([]Product, error)
	ListProductsByCategoryID(ctx context.Context, arg ListProductsByCategoryIDParams) ([]Product, error)
	ListProductsByVendorID(ctx context.Context, arg ListProductsByVendorIDParams) ([]Product, error)
	ListVendorUsers(ctx context.Context, arg ListVendorUsersParams) ([]VendorUser, error)
	ListVendors(ctx context.Context, arg ListVendorsParams) ([]Vendor, error)
	ListZones(ctx context.Context, arg ListZonesParams) ([]Zone, error)
	ListZonesByBrandID(ctx context.Context, arg ListZonesByBrandIDParams) ([]Zone, error)
	SearchBrandCategories(ctx context.Context, arg SearchBrandCategoriesParams) ([]BrandCategory, error)
	SearchCategories(ctx context.Context, arg SearchCategoriesParams) ([]Category, error)
	SearchInventoryHistory(ctx context.Context, arg SearchInventoryHistoryParams) ([]InventoryHistory, error)
	SearchProductInventory(ctx context.Context, arg SearchProductInventoryParams) ([]ProductInventory, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	SearchProductsByBrandID(ctx context.Context, arg SearchProductsByBrandIDParams) ([]Product, error)
	SearchProductsByCategoryID(ctx context.Context, arg SearchProductsByCategoryIDParams) ([]Product, error)
	SearchVendors(ctx context.Context, arg SearchVendorsParams) ([]Vendor, error)
	SearchZones(ctx context.Context, arg SearchZonesParams) ([]Zone, error)
	SearchZonesByBrandID(ctx context.Context, arg SearchZonesByBrandIDParams) ([]Zone, error)
	SearchZonesByGeoPoint(ctx context.Context, arg SearchZonesByGeoPointParams) ([]Zone, error)
	SearchZonesByGeoPointAndBrandID(ctx context.Context, arg SearchZonesByGeoPointAndBrandIDParams) ([]Zone, error)
	SearchZonesByGeoPolygon(ctx context.Context, arg SearchZonesByGeoPolygonParams) ([]Zone, error)
	SearchZonesByGeoPolygonAndBrandID(ctx context.Context, arg SearchZonesByGeoPolygonAndBrandIDParams) ([]Zone, error)
	UpdateBrand(ctx context.Context, arg UpdateBrandParams) (Brand, error)
	UpdateBrandCategory(ctx context.Context, arg UpdateBrandCategoryParams) (BrandCategory, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateInventoryHistory(ctx context.Context, arg UpdateInventoryHistoryParams) (InventoryHistory, error)
	UpdateOperationTime(ctx context.Context, arg UpdateOperationTimeParams) (OperationTime, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductInventory(ctx context.Context, arg UpdateProductInventoryParams) (ProductInventory, error)
	UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error)
	UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error)
	UpdateVendorUser(ctx context.Context, arg UpdateVendorUserParams) (VendorUser, error)
	UpdateZone(ctx context.Context, arg UpdateZoneParams) (Zone, error)
}

var _ Querier = (*Queries)(nil)
