// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0
// source: vendor_user.sql

package db

import (
	"context"
	"time"
)

const createVendorUser = `-- name: CreateVendorUser :one
INSERT INTO vendor_users (
  username,
  full_name,
  email,
  hashed_password,
  password_changed_at,
  role,
  vendor_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, username, full_name, email, hashed_password, password_changed_at, role, vendor_id, created_at
`

type CreateVendorUserParams struct {
	Username          string    `json:"username"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	Role              string    `json:"role"`
	VendorID          int64     `json:"vendor_id"`
}

func (q *Queries) CreateVendorUser(ctx context.Context, arg CreateVendorUserParams) (VendorUser, error) {
	row := q.queryRow(ctx, q.createVendorUserStmt, createVendorUser,
		arg.Username,
		arg.FullName,
		arg.Email,
		arg.HashedPassword,
		arg.PasswordChangedAt,
		arg.Role,
		arg.VendorID,
	)
	var i VendorUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.Role,
		&i.VendorID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVendorUser = `-- name: DeleteVendorUser :exec
DELETE FROM vendor_users WHERE id = $1
`

func (q *Queries) DeleteVendorUser(ctx context.Context, id int64) error {
	_, err := q.exec(ctx, q.deleteVendorUserStmt, deleteVendorUser, id)
	return err
}

const getVendorUser = `-- name: GetVendorUser :one
SELECT id, username, full_name, email, hashed_password, password_changed_at, role, vendor_id, created_at FROM vendor_users WHERE id = $1
`

func (q *Queries) GetVendorUser(ctx context.Context, id int64) (VendorUser, error) {
	row := q.queryRow(ctx, q.getVendorUserStmt, getVendorUser, id)
	var i VendorUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.Role,
		&i.VendorID,
		&i.CreatedAt,
	)
	return i, err
}

const getVendorUserByUsername = `-- name: GetVendorUserByUsername :one
SELECT id, username, full_name, email, hashed_password, password_changed_at, role, vendor_id, created_at FROM vendor_users WHERE username = $1
`

func (q *Queries) GetVendorUserByUsername(ctx context.Context, username string) (VendorUser, error) {
	row := q.queryRow(ctx, q.getVendorUserByUsernameStmt, getVendorUserByUsername, username)
	var i VendorUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.Role,
		&i.VendorID,
		&i.CreatedAt,
	)
	return i, err
}

const listVendorUsers = `-- name: ListVendorUsers :many
SELECT id, username, full_name, email, hashed_password, password_changed_at, role, vendor_id, created_at FROM vendor_users WHERE vendor_id = $1 ORDER BY id LIMIT $2 OFFSET $3
`

type ListVendorUsersParams struct {
	VendorID int64 `json:"vendor_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListVendorUsers(ctx context.Context, arg ListVendorUsersParams) ([]VendorUser, error) {
	rows, err := q.query(ctx, q.listVendorUsersStmt, listVendorUsers, arg.VendorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VendorUser{}
	for rows.Next() {
		var i VendorUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FullName,
			&i.Email,
			&i.HashedPassword,
			&i.PasswordChangedAt,
			&i.Role,
			&i.VendorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendorUser = `-- name: UpdateVendorUser :one
UPDATE vendor_users SET
  username = $2,
  full_name = $3,
  email = $4,
  hashed_password = $5,
  password_changed_at = $6,
  role = $7,
  vendor_id = $8
WHERE id = $1 
RETURNING id, username, full_name, email, hashed_password, password_changed_at, role, vendor_id, created_at
`

type UpdateVendorUserParams struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	HashedPassword    string    `json:"hashed_password"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	Role              string    `json:"role"`
	VendorID          int64     `json:"vendor_id"`
}

func (q *Queries) UpdateVendorUser(ctx context.Context, arg UpdateVendorUserParams) (VendorUser, error) {
	row := q.queryRow(ctx, q.updateVendorUserStmt, updateVendorUser,
		arg.ID,
		arg.Username,
		arg.FullName,
		arg.Email,
		arg.HashedPassword,
		arg.PasswordChangedAt,
		arg.Role,
		arg.VendorID,
	)
	var i VendorUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.PasswordChangedAt,
		&i.Role,
		&i.VendorID,
		&i.CreatedAt,
	)
	return i, err
}
